version: 2.1
jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Setup Code Climate test-reporter
          command: |
            # download test reporter as a static binary
              curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
              chmod +x ./cc-test-reporter
              ./cc-test-reporter before-build
      - run:
          command: |
            mkdir test-results
            poetry run coverage run -m pytest --junitxml=test-results/junit.xml
          name: Test it
      - store_test_results:
          path: test-results
      - run:
          name: Upload coverage to code climate
          command: |
            poetry run coverage xml
            ./cc-test-reporter after-build
orbs:
  python: circleci/python@1.0.0
workflows:
  main:
    jobs:
      - build